import { GetServerSideProps } from "next";
import styles from "./index.module.css";
import { getProviders, signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { AppProps } from "next/app";

export default function Home( { providers }: { providers: AppProps }) {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Courriel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-ministere-sante.ico" />
      </Head>
      <main>
        <h1 className={styles.mainTitle}>REGISTRE BUREAU D'ORDRE</h1>
        {!sessionData && <LoginContainer {...providers} />}
        
        
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}

function LoginContainer(providers: AppProps) {
  return (
    <div className={styles.loginContainer}>
      {Object.values(providers).map((provider) => (
        <button className={styles.loginButton} key={provider.id} onClick={() => signIn(provider.id, {
          callbackUrl: `${window.location.origin}`
        })} >Connectez vous avec google</button>
      ))}
    </div>
  )
}