import { GetServerSideProps } from "next";
import styles from "./index.module.css";
import { getProviders, signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { AppProps } from "next/app";
import SideBar from "~/components/SideBar";
import { InfoBox } from "~/components/InfoBox";

export default function Home( { providers }: { providers: AppProps }) {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData } = useSession();
  console.log(sessionData)
  return (
    <>
      <Head>
        <title>Courriel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo-ministere-sante.ico" />
      </Head>
      <div className={styles.headContainer}>
        {!sessionData && <LoginContainer {...providers} />}
        {sessionData && (
          <>
            <SideBar />
            <div className={styles.homeContainer}>
              <h1 className={styles.mainTitle}>REGISTRE BUREAU D'ORDRE</h1>
              <div className={styles.infoContainer}>
                <InfoBox title="Nombre de courriel envoyé aujourd'hui" value={5} important={4} />
                <InfoBox title="Nombre de courriel recu aujourd'hui" value={3} important={4} />
                <InfoBox title="Nombre de courriel envoyé cette semaine" value={14} important={4} />
                <InfoBox title="Nombre de courriel recu cette semaine" value={32} important={4} />
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}

function LoginContainer(providers: AppProps) {
  return (
    <div className={styles.loginContainer}>
      {Object.values(providers).map((provider) => (
        <button className={styles.loginButton} key={provider.id} onClick={() => signIn(provider.id, {
          callbackUrl: `${window.location.origin}`
        })} >Connectez vous avec google</button>
      ))}
    </div>
  )
}